owner: ageg-status
repo: ageg-status.github.io
user-agent: mdaoustudes

sites:
  - name: AGEG website
    url: https://www.ageg.ca/
    icon: https://www.ageg.ca/wp-content/uploads/2019/06/cropped-59079205_1502880046509656_7925612428161712128_n-192x192.png
    maxResponseTime: 2000
  - name: UdeS website
    url: https://www.usherbrooke.ca/
    icon: https://www.usherbrooke.ca/favicon.ico
    maxResponseTime: 1000
  - name: 2 Minutes de génie (prod)
    url: https://2mdg.ageg.ca/
    icon: https://2mdg.ageg.ca/images/logo-2mg.png
    maxResponseTime: 750
  - name: 2 Minutes de génie (gitlab page)
    url: https://2mdg.gitlab.io/
    icon: https://about.gitlab.com/ico/favicon.ico
    maxResponseTime: 750
  - name: 2 Minutes de génie (staging)
    url: https://2mdgstaging.gitlab.io/
    icon: https://about.gitlab.com/ico/favicon.ico
    maxResponseTime: 750

assignees:
  - mdaoustudes

status-website:
  cname: ageg-status.github.io
  logoUrl: https://www.ageg.ca/wp-content/uploads/2019/06/cropped-59079205_1502880046509656_7925612428161712128_n-1.png
  name: AGEG status
  introTitle: "Status page for AGEG related websites"
  theme: dark
  navbar:
    - title: UdeS status
      href: https://etatdesservices.usherbrooke.ca/

workflowSchedule:
  graphs: "0 0 * * *" #At 00:00.
  responseTime: "0 23 * * *" #At 23:00.
  staticSite: "0 1 * * *" #At 01:00.
  summary: "0 0 * * *" #At 00:00.
  updateTemplate: "0 0 * * *" #At 00:00.
  updates: "0 3 * * *" #At 03:00.
  uptime: "*/5 * * * *" #At every 5th minute.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
